CREATE TABLE h19_07_ora.apex$_ws_webpg_sections (
  "ID" NUMBER NOT NULL,
  ws_app_id NUMBER NOT NULL,
  webpage_id NUMBER,
  display_sequence NUMBER,
  section_type VARCHAR2(30 BYTE) NOT NULL CONSTRAINT apex$_ws_webpg_section_type_ck CHECK (section_type in ('TEXT','DATA','CHART','NAV_PAGE','NAV_SECTION')),
  title VARCHAR2(4000 BYTE),
  "CONTENT" CLOB,
  content_upper CLOB,
  nav_start_webpage_id NUMBER,
  nav_max_level NUMBER,
  nav_include_link VARCHAR2(1 BYTE) CONSTRAINT apex$_ws_webpg_section_link_ck CHECK (nav_include_link in ('Y','N')),
  data_grid_id NUMBER,
  report_id NUMBER,
  data_section_style NUMBER,
  chart_type VARCHAR2(255 BYTE),
  chart_3d VARCHAR2(1 BYTE) CONSTRAINT apex$_ws_webpg_section_3d_ck CHECK (chart_3d in ('Y','N')),
  chart_label VARCHAR2(255 BYTE),
  label_axis_title VARCHAR2(255 BYTE),
  chart_value VARCHAR2(255 BYTE),
  value_axis_title VARCHAR2(255 BYTE),
  chart_aggregate VARCHAR2(255 BYTE),
  chart_sorting VARCHAR2(255 BYTE),
  created_on DATE NOT NULL,
  created_by VARCHAR2(255 BYTE) NOT NULL,
  updated_on DATE,
  updated_by VARCHAR2(255 BYTE),
  CONSTRAINT apex$_ws_webpg_sections_pk PRIMARY KEY ("ID")
);