CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[PREPRO] [real] NULL,
[CATPRO] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[CANTPRO] [int] NULL,
[FECHINGPRO] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
