CREATE TABLE [dbo].[VENTA]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[NOMCLI] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[DNICLI] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[FECVENT] [date] NULL,
[IDPER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED  ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
