CREATE TABLE [dbo].[ASIGNACION]
(
[IDASI] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NULL,
[IDSUC] [int] NULL,
[ESTASI] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDVEN] [int] NULL,
[GRUASIG] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASIGNACION] ADD CONSTRAINT [ASIGNACION_pk] PRIMARY KEY CLUSTERED  ([IDASI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASIGNACION] ADD CONSTRAINT [ASIGNACION_PERSONA] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[ASIGNACION] ADD CONSTRAINT [ASIGNACION_PERSONA_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[ASIGNACION] ADD CONSTRAINT [SUCURSAL_DETALLE_SUCURSAL] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
