CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDTEL] [int] NOT NULL IDENTITY(1, 1),
[CANTVENTDET] [int] NULL,
[IDPRO] [int] NULL,
[IDVENT] [int] NULL,
[ESTVEND] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED  ([IDTEL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVENT]) REFERENCES [dbo].[VENTA] ([IDVENT])
GO
