CREATE TABLE [MAESTRA].[EQUIPOS]
(
[CODEQU] [int] NOT NULL IDENTITY(1, 1),
[NOMEQU] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[MODEQU] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CATEQU] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[IMEIEQU] [char] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CODSTO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [MAESTRA].[EQUIPOS] ADD CONSTRAINT [PK__EQUIPOS__CF9E02D56CBBA7C9] PRIMARY KEY CLUSTERED  ([CODEQU]) ON [PRIMARY]
GO
ALTER TABLE [MAESTRA].[EQUIPOS] ADD CONSTRAINT [STOCK_EQUIPO_CODSTO] FOREIGN KEY ([CODSTO]) REFERENCES [VENTAS].[STOCK] ([CODSTO])
GO
