CREATE TABLE [MAESTRA].[SUCURSAL]
(
[CODSUC] [int] NOT NULL IDENTITY(1, 1),
[DIRSUC] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[TELSUC] [char] (9) COLLATE Modern_Spanish_CI_AS NULL,
[IDPER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [MAESTRA].[SUCURSAL] ADD CONSTRAINT [PK__SUCURSAL__B76057D5D6826772] PRIMARY KEY CLUSTERED  ([CODSUC]) ON [PRIMARY]
GO
ALTER TABLE [MAESTRA].[SUCURSAL] ADD CONSTRAINT [PERSONA_SUCURSAL_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [MAESTRA].[PERSONA] ([IDPER])
GO
