CREATE TABLE [VENTAS].[STOCK]
(
[CODSTO] [int] NOT NULL IDENTITY(1, 1),
[FECHEMTSTO] [date] NULL,
[CANTSTO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTAS].[STOCK] ADD CONSTRAINT [PK__STOCK__B7605F826D865CAC] PRIMARY KEY CLUSTERED  ([CODSTO]) ON [PRIMARY]
GO
